name: CI Pipeline
on:
  push:
    branches:
    - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Version
        run: node --version

      - name: Install Packages
        run: yarn install --immutable

      - name: Test Packages
        run: yarn run test:ci
