name: Snyk Scan
on:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk
        uses: ./actions/snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
